apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-api.fullname" . }}
  labels:
    {{- include "generic-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "generic-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "generic-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
