location ~ /\.(?!well-known)(?:.*)$ {
    deny all;
    access_log off;
    log_not_found off;
}

location ~* \.(?:bak|config|conf|dist|env|ini|log|old|orig|save|sql|swp|tmp)$ {
    deny all;
    access_log off;
    log_not_found off;
}

location ~* /(?:\.git|\.hg|\.svn|CVS)(?:/|$) {
    deny all;
    access_log off;
    log_not_found off;
}
