global:
  scrape_interval: 1s
  evaluation_interval: 1s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 192.168.101.102:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["192.168.101.102:9090"]
  - job_name: simple_server
    static_configs:
      - targets: ["192.168.101.102:8090"]
  - job_name: node_exporter
    static_configs:
      - targets: ["192.168.101.102:9100"]
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'  # Spring Boot 暴露的 Prometheus 路径
    static_configs:
      - targets: ['192.168.101.102:8082']  # 替换为你的 Spring Boot 应用地址
  - job_name: 'spring-boot-app-1'
    metrics_path: '/actuator/prometheus'  # Spring Boot 暴露的 Prometheus 路径
    static_configs:
      - targets: ['192.168.101.102:8083']  # 替换为你的 Spring Boot 应用地址