replicaCount: 1

image:
  repository: 192.168.50.18:5000/API-NAME
  tag: "TAG"
  pullPolicy: Always

imagePullSecrets: []
podAnnotations: {}
podLabels: {}

container:
  port: API_PORT

env: []

resources: {}

probes:
  enabled: false
  path: /actuator/health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

service:
  port: API_PORT
  annotations: {}

prometheus:
  path: /actuator/prometheus
  port: http
  interval: 30s
  scrapeTimeout: 10s
  scheme: http
  annotations:
    enabled: false
  serviceMonitor:
    enabled: true
    namespace: ""
    namespaceSelector: {}
    labels: {}
    annotations: {}
    relabelings: []
    metricRelabelings: []

route:
  enabled: true
  gatewayName: traefik-gateway
  gatewayNamespace: kube-system
  hostname: HOSTNAME
  path: /

nodeSelector: {}
tolerations: []
affinity: {}
