apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-api.fullname" . }}
  labels:
    {{- include "springboot-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "springboot-api.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "springboot-api.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: {{ include "springboot-api.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: "{{ .Values.service.targetPort }}"
{{- with .Values.env }}
{{- toYaml . | nindent 12 -}}
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.config.applicationProperties }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
{{- end }}
          {{- if .Values.probe.enabled }}
          livenessProbe:
            httpGet:
              path: "{{ .Values.probe.livenessPath }}"
              port: http
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.probe.readinessPath }}"
              port: http
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
          {{- end }}
      {{- if .Values.config.applicationProperties }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "springboot-api.fullname" . }}-config
            items:
              - key: application.properties
                path: application.properties
      {{- end }}

