apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-api.fullname" . }}
  labels:
    {{- include "springboot-api.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.prometheus.annotations.enabled }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.prometheus.annotations.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/path: {{ .Values.prometheus.path | quote }}
    prometheus.io/port: {{ .Values.service.port | quote }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "springboot-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
