apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "springboot-api.fullname" . }}
  labels:
    release: prometheus   # ⚠️ 必须和 Prometheus 匹配
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "springboot-api.fullname" . }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s