replicaCount: 1

image:
  repository: 192.168.50.18:5000/API-NAME
  tag: "TAG"
  pullPolicy: IfNotPresent

imagePullSecrets: []
podAnnotations: {}
podLabels: {}

container:
  port: 80

env: []

resources: {}

service:
  port: 80
  annotations: {}

prometheus:
  path: /metrics
  port: http
  interval: 30s
  scrapeTimeout: 10s
  scheme: http
  annotations:
    enabled: false
  serviceMonitor:
    enabled: false
    namespace: ""
    namespaceSelector: {}
    labels: {}
    annotations: {}
    relabelings: []
    metricRelabelings: []

route:
  enabled: true
  gatewayName: traefik-gateway
  gatewayNamespace: kube-system
  hostname: HOSTNAME
  path: /

nodeSelector: {}
tolerations: []
affinity: {}
