replicaCount: 1

image:
  repository: 192.168.50.18:5000/API-NAME
  tag: "TAG"
  pullPolicy: IfNotPresent

imagePullSecrets: []
podAnnotations: {}
podLabels: {}

container:
  port: 80

env: []

resources: {}

service:
  port: 80

route:
  enabled: true
  gatewayName: traefik-gateway
  gatewayNamespace: kube-system
  hostname: HOSTNAME
  path: /

nodeSelector: {}
tolerations: []
affinity: {}
